spring:
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false 
    driverClassName: org.h2.Driver
    username: sa
    password: 123456
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console